name: 2. Парсинг в lst

on:
  workflow_run:
    workflows: ["1. Сборка geodata и маршрутизации"]
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: write

jobs:
  parse-data:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    env:
      TARGET_BRANCH: ${{ github.event.workflow_run.head_branch || github.ref_name }}
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v4
        with:
          ref: ${{ env.TARGET_BRANCH }}
          fetch-depth: 0

      - name: Настройка Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Настройка Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Установка зависимостей
        run: pip install protobuf

      - name: Компиляция Protobuf схемы
        run: protoc --python_out=. tools/router.proto

      - name: Запуск скрипта парсера
        run: python tools/parser.py
        env:
          GITHUB_REF_NAME: ${{ env.TARGET_BRANCH }}

      - name: Подготовка папки result/lists для test
        if: env.TARGET_BRANCH == 'test'
        run: |
          mkdir -p result/lists
          cp -r parser-tmp/* result/lists/

      - name: Деплой для ветки main в ветку lists (чистый деплой)
        if: env.TARGET_BRANCH == 'main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: lists
          folder: parser-tmp
          clean: true
          single-commit: true

      - name: Деплой для ветки test в result/lists (внутри test)
        if: env.TARGET_BRANCH == 'test'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add result/lists/
          git commit -m "chore: обновление списков (test) [skip ci]" || echo "Нет изменений для коммита"
          git push origin test
